function [fitresult, gof] = createFit(age, chd)
%CREATEFIT(AGE,CHD)
%  Create a fit.
%
%  Data for 'Framingham 10 Year CHD Risk' fit:
%      X Input : age
%      Y Output: chd
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Mar-2013 11:25:17


%% Fit: 'Framingham 10 Year CHD Risk'.
age = [67:71]';
chd = [0.098 0.098 0.115 0.077 0.114]';
[xData, yData] = prepareCurveData( age, chd );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Framingham 10 Year CHD Risk' );
h = plot( fitresult, xData, yData);
legend( h, 'chd vs. age', 'Framingham 10 Year CHD Risk', 'Location', 'NorthEast' );
% Label axes
xlabel( 'age' );
ylabel( 'chd' );
grid on


